import { saveOrder } from './store.js';

const modal = document.getElementById('confirmationModal');
const closeButton = document.querySelector('.close-button');
const orderNumberSpan = document.getElementById('orderNumber');

closeButton.addEventListener('click', () => {
  modal.style.display = 'none';
});

window.addEventListener('click', (event) => {
  if (event.target === modal) {
    modal.style.display = 'none';
  }
});

export async function checkout(order) {
  try {
    const docRef = await saveOrder(order);
    // The official order number is generated by a cloud function and sent via email.
    // We use the document ID as a temporary reference for the user on the screen.
    orderNumberSpan.textContent = docRef.id;
    modal.style.display = 'block';
  } catch (error) {
    console.error("Error during checkout: ", error);
    // For a better user experience, you could import the `showMessage` function
    // from a shared UI module instead of using a generic alert.
    alert('There was an error placing your order. Please try again.');
  }
}
